# .github/workflows/demo.yml

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "dev" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  merge-branches:
    name: Merge main into develop
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Push from dev
        run: echo "Per release"
      
      - name: Test Local Action
        uses: tommorales/github_cdci@v1
        with:
          token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          branches: main
          force: true
   
